/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const AppsLazyRouteImport = createFileRoute('/apps')()
const IndexLazyRouteImport = createFileRoute('/')()
const AppsVezhamBooksLazyRouteImport = createFileRoute('/apps/vezham-books')()
const AppsExploreIndexLazyRouteImport = createFileRoute('/apps/explore/')()
const AppsExplore1IndexLazyRouteImport = createFileRoute('/apps/explore-1/')()
const AppsExploreExploreIdLazyRouteImport = createFileRoute(
  '/apps/explore/$exploreId',
)()
const AppsExplore1AppExploreIdLazyRouteImport = createFileRoute(
  '/apps/explore-1/$appExploreId',
)()

const AppsLazyRoute = AppsLazyRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/apps.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AppsVezhamBooksLazyRoute = AppsVezhamBooksLazyRouteImport.update({
  id: '/vezham-books',
  path: '/vezham-books',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() =>
  import('./routes/apps/vezham-books.lazy').then((d) => d.Route),
)
const AppsExploreIndexLazyRoute = AppsExploreIndexLazyRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() =>
  import('./routes/apps/explore/index.lazy').then((d) => d.Route),
)
const AppsExplore1IndexLazyRoute = AppsExplore1IndexLazyRouteImport.update({
  id: '/explore-1/',
  path: '/explore-1/',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() =>
  import('./routes/apps/explore-1/index.lazy').then((d) => d.Route),
)
const AppsExploreExploreIdLazyRoute =
  AppsExploreExploreIdLazyRouteImport.update({
    id: '/explore/$exploreId',
    path: '/explore/$exploreId',
    getParentRoute: () => AppsLazyRoute,
  } as any).lazy(() =>
    import('./routes/apps/explore/$exploreId.lazy').then((d) => d.Route),
  )
const AppsExplore1AppExploreIdLazyRoute =
  AppsExplore1AppExploreIdLazyRouteImport.update({
    id: '/explore-1/$appExploreId',
    path: '/explore-1/$appExploreId',
    getParentRoute: () => AppsLazyRoute,
  } as any).lazy(() =>
    import('./routes/apps/explore-1/$appExploreId.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/apps': typeof AppsLazyRouteWithChildren
  '/apps/vezham-books': typeof AppsVezhamBooksLazyRoute
  '/apps/explore-1/$appExploreId': typeof AppsExplore1AppExploreIdLazyRoute
  '/apps/explore/$exploreId': typeof AppsExploreExploreIdLazyRoute
  '/apps/explore-1': typeof AppsExplore1IndexLazyRoute
  '/apps/explore': typeof AppsExploreIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/apps': typeof AppsLazyRouteWithChildren
  '/apps/vezham-books': typeof AppsVezhamBooksLazyRoute
  '/apps/explore-1/$appExploreId': typeof AppsExplore1AppExploreIdLazyRoute
  '/apps/explore/$exploreId': typeof AppsExploreExploreIdLazyRoute
  '/apps/explore-1': typeof AppsExplore1IndexLazyRoute
  '/apps/explore': typeof AppsExploreIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/apps': typeof AppsLazyRouteWithChildren
  '/apps/vezham-books': typeof AppsVezhamBooksLazyRoute
  '/apps/explore-1/$appExploreId': typeof AppsExplore1AppExploreIdLazyRoute
  '/apps/explore/$exploreId': typeof AppsExploreExploreIdLazyRoute
  '/apps/explore-1/': typeof AppsExplore1IndexLazyRoute
  '/apps/explore/': typeof AppsExploreIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/apps/vezham-books'
    | '/apps/explore-1/$appExploreId'
    | '/apps/explore/$exploreId'
    | '/apps/explore-1'
    | '/apps/explore'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/apps/vezham-books'
    | '/apps/explore-1/$appExploreId'
    | '/apps/explore/$exploreId'
    | '/apps/explore-1'
    | '/apps/explore'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/apps/vezham-books'
    | '/apps/explore-1/$appExploreId'
    | '/apps/explore/$exploreId'
    | '/apps/explore-1/'
    | '/apps/explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AppsLazyRoute: typeof AppsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/vezham-books': {
      id: '/apps/vezham-books'
      path: '/vezham-books'
      fullPath: '/apps/vezham-books'
      preLoaderRoute: typeof AppsVezhamBooksLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
    '/apps/explore/': {
      id: '/apps/explore/'
      path: '/explore'
      fullPath: '/apps/explore'
      preLoaderRoute: typeof AppsExploreIndexLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
    '/apps/explore-1/': {
      id: '/apps/explore-1/'
      path: '/explore-1'
      fullPath: '/apps/explore-1'
      preLoaderRoute: typeof AppsExplore1IndexLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
    '/apps/explore/$exploreId': {
      id: '/apps/explore/$exploreId'
      path: '/explore/$exploreId'
      fullPath: '/apps/explore/$exploreId'
      preLoaderRoute: typeof AppsExploreExploreIdLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
    '/apps/explore-1/$appExploreId': {
      id: '/apps/explore-1/$appExploreId'
      path: '/explore-1/$appExploreId'
      fullPath: '/apps/explore-1/$appExploreId'
      preLoaderRoute: typeof AppsExplore1AppExploreIdLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
  }
}

interface AppsLazyRouteChildren {
  AppsVezhamBooksLazyRoute: typeof AppsVezhamBooksLazyRoute
  AppsExplore1AppExploreIdLazyRoute: typeof AppsExplore1AppExploreIdLazyRoute
  AppsExploreExploreIdLazyRoute: typeof AppsExploreExploreIdLazyRoute
  AppsExplore1IndexLazyRoute: typeof AppsExplore1IndexLazyRoute
  AppsExploreIndexLazyRoute: typeof AppsExploreIndexLazyRoute
}

const AppsLazyRouteChildren: AppsLazyRouteChildren = {
  AppsVezhamBooksLazyRoute: AppsVezhamBooksLazyRoute,
  AppsExplore1AppExploreIdLazyRoute: AppsExplore1AppExploreIdLazyRoute,
  AppsExploreExploreIdLazyRoute: AppsExploreExploreIdLazyRoute,
  AppsExplore1IndexLazyRoute: AppsExplore1IndexLazyRoute,
  AppsExploreIndexLazyRoute: AppsExploreIndexLazyRoute,
}

const AppsLazyRouteWithChildren = AppsLazyRoute._addFileChildren(
  AppsLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AppsLazyRoute: AppsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
