/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const AppsLazyRouteImport = createFileRoute('/apps')()
const IndexLazyRouteImport = createFileRoute('/')()
const AppsVezhamBooksLazyRouteImport = createFileRoute('/apps/vezham-books')()
const AppsExplore1LazyRouteImport = createFileRoute('/apps/explore-1')()
const AppsExploreLazyRouteImport = createFileRoute('/apps/explore')()
const AppsAppIdLazyRouteImport = createFileRoute('/apps/$appId')()
const AppsAppExploreIdLazyRouteImport = createFileRoute('/apps/$appExploreId')()

const AppsLazyRoute = AppsLazyRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/apps.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AppsVezhamBooksLazyRoute = AppsVezhamBooksLazyRouteImport.update({
  id: '/vezham-books',
  path: '/vezham-books',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() =>
  import('./routes/apps/vezham-books.lazy').then((d) => d.Route),
)
const AppsExplore1LazyRoute = AppsExplore1LazyRouteImport.update({
  id: '/explore-1',
  path: '/explore-1',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() =>
  import('./routes/apps/explore-1.lazy').then((d) => d.Route),
)
const AppsExploreLazyRoute = AppsExploreLazyRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() => import('./routes/apps/explore.lazy').then((d) => d.Route))
const AppsAppIdLazyRoute = AppsAppIdLazyRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() => import('./routes/apps/$appId.lazy').then((d) => d.Route))
const AppsAppExploreIdLazyRoute = AppsAppExploreIdLazyRouteImport.update({
  id: '/$appExploreId',
  path: '/$appExploreId',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() =>
  import('./routes/apps/$appExploreId.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/apps': typeof AppsLazyRouteWithChildren
  '/apps/$appExploreId': typeof AppsAppExploreIdLazyRoute
  '/apps/$appId': typeof AppsAppIdLazyRoute
  '/apps/explore': typeof AppsExploreLazyRoute
  '/apps/explore-1': typeof AppsExplore1LazyRoute
  '/apps/vezham-books': typeof AppsVezhamBooksLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/apps': typeof AppsLazyRouteWithChildren
  '/apps/$appExploreId': typeof AppsAppExploreIdLazyRoute
  '/apps/$appId': typeof AppsAppIdLazyRoute
  '/apps/explore': typeof AppsExploreLazyRoute
  '/apps/explore-1': typeof AppsExplore1LazyRoute
  '/apps/vezham-books': typeof AppsVezhamBooksLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/apps': typeof AppsLazyRouteWithChildren
  '/apps/$appExploreId': typeof AppsAppExploreIdLazyRoute
  '/apps/$appId': typeof AppsAppIdLazyRoute
  '/apps/explore': typeof AppsExploreLazyRoute
  '/apps/explore-1': typeof AppsExplore1LazyRoute
  '/apps/vezham-books': typeof AppsVezhamBooksLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/apps/$appExploreId'
    | '/apps/$appId'
    | '/apps/explore'
    | '/apps/explore-1'
    | '/apps/vezham-books'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/apps/$appExploreId'
    | '/apps/$appId'
    | '/apps/explore'
    | '/apps/explore-1'
    | '/apps/vezham-books'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/apps/$appExploreId'
    | '/apps/$appId'
    | '/apps/explore'
    | '/apps/explore-1'
    | '/apps/vezham-books'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AppsLazyRoute: typeof AppsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/vezham-books': {
      id: '/apps/vezham-books'
      path: '/vezham-books'
      fullPath: '/apps/vezham-books'
      preLoaderRoute: typeof AppsVezhamBooksLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
    '/apps/explore-1': {
      id: '/apps/explore-1'
      path: '/explore-1'
      fullPath: '/apps/explore-1'
      preLoaderRoute: typeof AppsExplore1LazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
    '/apps/explore': {
      id: '/apps/explore'
      path: '/explore'
      fullPath: '/apps/explore'
      preLoaderRoute: typeof AppsExploreLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
    '/apps/$appExploreId': {
      id: '/apps/$appExploreId'
      path: '/$appExploreId'
      fullPath: '/apps/$appExploreId'
      preLoaderRoute: typeof AppsAppExploreIdLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
  }
}

interface AppsLazyRouteChildren {
  AppsAppExploreIdLazyRoute: typeof AppsAppExploreIdLazyRoute
  AppsAppIdLazyRoute: typeof AppsAppIdLazyRoute
  AppsExploreLazyRoute: typeof AppsExploreLazyRoute
  AppsExplore1LazyRoute: typeof AppsExplore1LazyRoute
  AppsVezhamBooksLazyRoute: typeof AppsVezhamBooksLazyRoute
}

const AppsLazyRouteChildren: AppsLazyRouteChildren = {
  AppsAppExploreIdLazyRoute: AppsAppExploreIdLazyRoute,
  AppsAppIdLazyRoute: AppsAppIdLazyRoute,
  AppsExploreLazyRoute: AppsExploreLazyRoute,
  AppsExplore1LazyRoute: AppsExplore1LazyRoute,
  AppsVezhamBooksLazyRoute: AppsVezhamBooksLazyRoute,
}

const AppsLazyRouteWithChildren = AppsLazyRoute._addFileChildren(
  AppsLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AppsLazyRoute: AppsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
