/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const AppsLazyRouteImport = createFileRoute('/apps')()
const IndexLazyRouteImport = createFileRoute('/')()
const AppsExploreLazyRouteImport = createFileRoute('/apps/explore')()
const AppsBooksLazyRouteImport = createFileRoute('/apps/books')()
const AppsAppIdLazyRouteImport = createFileRoute('/apps/$appId')()

const AppsLazyRoute = AppsLazyRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/apps.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AppsExploreLazyRoute = AppsExploreLazyRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() => import('./routes/apps/explore.lazy').then((d) => d.Route))
const AppsBooksLazyRoute = AppsBooksLazyRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() => import('./routes/apps/books.lazy').then((d) => d.Route))
const AppsAppIdLazyRoute = AppsAppIdLazyRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => AppsLazyRoute,
} as any).lazy(() => import('./routes/apps/$appId.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/apps': typeof AppsLazyRouteWithChildren
  '/apps/$appId': typeof AppsAppIdLazyRoute
  '/apps/books': typeof AppsBooksLazyRoute
  '/apps/explore': typeof AppsExploreLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/apps': typeof AppsLazyRouteWithChildren
  '/apps/$appId': typeof AppsAppIdLazyRoute
  '/apps/books': typeof AppsBooksLazyRoute
  '/apps/explore': typeof AppsExploreLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/apps': typeof AppsLazyRouteWithChildren
  '/apps/$appId': typeof AppsAppIdLazyRoute
  '/apps/books': typeof AppsBooksLazyRoute
  '/apps/explore': typeof AppsExploreLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apps' | '/apps/$appId' | '/apps/books' | '/apps/explore'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apps' | '/apps/$appId' | '/apps/books' | '/apps/explore'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/apps/$appId'
    | '/apps/books'
    | '/apps/explore'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AppsLazyRoute: typeof AppsLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/explore': {
      id: '/apps/explore'
      path: '/explore'
      fullPath: '/apps/explore'
      preLoaderRoute: typeof AppsExploreLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
    '/apps/books': {
      id: '/apps/books'
      path: '/books'
      fullPath: '/apps/books'
      preLoaderRoute: typeof AppsBooksLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdLazyRouteImport
      parentRoute: typeof AppsLazyRoute
    }
  }
}

interface AppsLazyRouteChildren {
  AppsAppIdLazyRoute: typeof AppsAppIdLazyRoute
  AppsBooksLazyRoute: typeof AppsBooksLazyRoute
  AppsExploreLazyRoute: typeof AppsExploreLazyRoute
}

const AppsLazyRouteChildren: AppsLazyRouteChildren = {
  AppsAppIdLazyRoute: AppsAppIdLazyRoute,
  AppsBooksLazyRoute: AppsBooksLazyRoute,
  AppsExploreLazyRoute: AppsExploreLazyRoute,
}

const AppsLazyRouteWithChildren = AppsLazyRoute._addFileChildren(
  AppsLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AppsLazyRoute: AppsLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
