/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const SignupLazyRouteImport = createFileRoute('/signup')()
const LoginLazyRouteImport = createFileRoute('/login')()
const IndexLazyRouteImport = createFileRoute('/')()
const VezhamResourcesLazyRouteImport = createFileRoute('/vezham/resources')()
const VezhamPricingLazyRouteImport = createFileRoute('/vezham/pricing')()
const VezhamFeaturesLazyRouteImport = createFileRoute('/vezham/features')()
const VezhamResourcesIndexLazyRouteImport =
  createFileRoute('/vezham/resources/')()
const VezhamFeaturesIndexLazyRouteImport =
  createFileRoute('/vezham/features/')()
const VezhamResourcesSupportLazyRouteImport = createFileRoute(
  '/vezham/resources/support',
)()
const VezhamResourcesHelpCenterLazyRouteImport = createFileRoute(
  '/vezham/resources/help-center',
)()
const VezhamFeaturesFeatureIdLazyRouteImport = createFileRoute(
  '/vezham/features/$featureId',
)()

const SignupLazyRoute = SignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const VezhamResourcesLazyRoute = VezhamResourcesLazyRouteImport.update({
  id: '/vezham/resources',
  path: '/vezham/resources',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/vezham/resources.lazy').then((d) => d.Route),
)
const VezhamPricingLazyRoute = VezhamPricingLazyRouteImport.update({
  id: '/vezham/pricing',
  path: '/vezham/pricing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/vezham/pricing.lazy').then((d) => d.Route),
)
const VezhamFeaturesLazyRoute = VezhamFeaturesLazyRouteImport.update({
  id: '/vezham/features',
  path: '/vezham/features',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/vezham/features.lazy').then((d) => d.Route),
)
const VezhamResourcesIndexLazyRoute =
  VezhamResourcesIndexLazyRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => VezhamResourcesLazyRoute,
  } as any).lazy(() =>
    import('./routes/vezham/resources/index.lazy').then((d) => d.Route),
  )
const VezhamFeaturesIndexLazyRoute = VezhamFeaturesIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VezhamFeaturesLazyRoute,
} as any).lazy(() =>
  import('./routes/vezham/features/index.lazy').then((d) => d.Route),
)
const VezhamResourcesSupportLazyRoute =
  VezhamResourcesSupportLazyRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => VezhamResourcesLazyRoute,
  } as any).lazy(() =>
    import('./routes/vezham/resources/support.lazy').then((d) => d.Route),
  )
const VezhamResourcesHelpCenterLazyRoute =
  VezhamResourcesHelpCenterLazyRouteImport.update({
    id: '/help-center',
    path: '/help-center',
    getParentRoute: () => VezhamResourcesLazyRoute,
  } as any).lazy(() =>
    import('./routes/vezham/resources/help-center.lazy').then((d) => d.Route),
  )
const VezhamFeaturesFeatureIdLazyRoute =
  VezhamFeaturesFeatureIdLazyRouteImport.update({
    id: '/$featureId',
    path: '/$featureId',
    getParentRoute: () => VezhamFeaturesLazyRoute,
  } as any).lazy(() =>
    import('./routes/vezham/features/$featureId.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/vezham/features': typeof VezhamFeaturesLazyRouteWithChildren
  '/vezham/pricing': typeof VezhamPricingLazyRoute
  '/vezham/resources': typeof VezhamResourcesLazyRouteWithChildren
  '/vezham/features/$featureId': typeof VezhamFeaturesFeatureIdLazyRoute
  '/vezham/resources/help-center': typeof VezhamResourcesHelpCenterLazyRoute
  '/vezham/resources/support': typeof VezhamResourcesSupportLazyRoute
  '/vezham/features/': typeof VezhamFeaturesIndexLazyRoute
  '/vezham/resources/': typeof VezhamResourcesIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/vezham/pricing': typeof VezhamPricingLazyRoute
  '/vezham/features/$featureId': typeof VezhamFeaturesFeatureIdLazyRoute
  '/vezham/resources/help-center': typeof VezhamResourcesHelpCenterLazyRoute
  '/vezham/resources/support': typeof VezhamResourcesSupportLazyRoute
  '/vezham/features': typeof VezhamFeaturesIndexLazyRoute
  '/vezham/resources': typeof VezhamResourcesIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/login': typeof LoginLazyRoute
  '/signup': typeof SignupLazyRoute
  '/vezham/features': typeof VezhamFeaturesLazyRouteWithChildren
  '/vezham/pricing': typeof VezhamPricingLazyRoute
  '/vezham/resources': typeof VezhamResourcesLazyRouteWithChildren
  '/vezham/features/$featureId': typeof VezhamFeaturesFeatureIdLazyRoute
  '/vezham/resources/help-center': typeof VezhamResourcesHelpCenterLazyRoute
  '/vezham/resources/support': typeof VezhamResourcesSupportLazyRoute
  '/vezham/features/': typeof VezhamFeaturesIndexLazyRoute
  '/vezham/resources/': typeof VezhamResourcesIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/vezham/features'
    | '/vezham/pricing'
    | '/vezham/resources'
    | '/vezham/features/$featureId'
    | '/vezham/resources/help-center'
    | '/vezham/resources/support'
    | '/vezham/features/'
    | '/vezham/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/vezham/pricing'
    | '/vezham/features/$featureId'
    | '/vezham/resources/help-center'
    | '/vezham/resources/support'
    | '/vezham/features'
    | '/vezham/resources'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/vezham/features'
    | '/vezham/pricing'
    | '/vezham/resources'
    | '/vezham/features/$featureId'
    | '/vezham/resources/help-center'
    | '/vezham/resources/support'
    | '/vezham/features/'
    | '/vezham/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  SignupLazyRoute: typeof SignupLazyRoute
  VezhamFeaturesLazyRoute: typeof VezhamFeaturesLazyRouteWithChildren
  VezhamPricingLazyRoute: typeof VezhamPricingLazyRoute
  VezhamResourcesLazyRoute: typeof VezhamResourcesLazyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vezham/resources': {
      id: '/vezham/resources'
      path: '/vezham/resources'
      fullPath: '/vezham/resources'
      preLoaderRoute: typeof VezhamResourcesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vezham/pricing': {
      id: '/vezham/pricing'
      path: '/vezham/pricing'
      fullPath: '/vezham/pricing'
      preLoaderRoute: typeof VezhamPricingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vezham/features': {
      id: '/vezham/features'
      path: '/vezham/features'
      fullPath: '/vezham/features'
      preLoaderRoute: typeof VezhamFeaturesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vezham/resources/': {
      id: '/vezham/resources/'
      path: '/'
      fullPath: '/vezham/resources/'
      preLoaderRoute: typeof VezhamResourcesIndexLazyRouteImport
      parentRoute: typeof VezhamResourcesLazyRoute
    }
    '/vezham/features/': {
      id: '/vezham/features/'
      path: '/'
      fullPath: '/vezham/features/'
      preLoaderRoute: typeof VezhamFeaturesIndexLazyRouteImport
      parentRoute: typeof VezhamFeaturesLazyRoute
    }
    '/vezham/resources/support': {
      id: '/vezham/resources/support'
      path: '/support'
      fullPath: '/vezham/resources/support'
      preLoaderRoute: typeof VezhamResourcesSupportLazyRouteImport
      parentRoute: typeof VezhamResourcesLazyRoute
    }
    '/vezham/resources/help-center': {
      id: '/vezham/resources/help-center'
      path: '/help-center'
      fullPath: '/vezham/resources/help-center'
      preLoaderRoute: typeof VezhamResourcesHelpCenterLazyRouteImport
      parentRoute: typeof VezhamResourcesLazyRoute
    }
    '/vezham/features/$featureId': {
      id: '/vezham/features/$featureId'
      path: '/$featureId'
      fullPath: '/vezham/features/$featureId'
      preLoaderRoute: typeof VezhamFeaturesFeatureIdLazyRouteImport
      parentRoute: typeof VezhamFeaturesLazyRoute
    }
  }
}

interface VezhamFeaturesLazyRouteChildren {
  VezhamFeaturesFeatureIdLazyRoute: typeof VezhamFeaturesFeatureIdLazyRoute
  VezhamFeaturesIndexLazyRoute: typeof VezhamFeaturesIndexLazyRoute
}

const VezhamFeaturesLazyRouteChildren: VezhamFeaturesLazyRouteChildren = {
  VezhamFeaturesFeatureIdLazyRoute: VezhamFeaturesFeatureIdLazyRoute,
  VezhamFeaturesIndexLazyRoute: VezhamFeaturesIndexLazyRoute,
}

const VezhamFeaturesLazyRouteWithChildren =
  VezhamFeaturesLazyRoute._addFileChildren(VezhamFeaturesLazyRouteChildren)

interface VezhamResourcesLazyRouteChildren {
  VezhamResourcesHelpCenterLazyRoute: typeof VezhamResourcesHelpCenterLazyRoute
  VezhamResourcesSupportLazyRoute: typeof VezhamResourcesSupportLazyRoute
  VezhamResourcesIndexLazyRoute: typeof VezhamResourcesIndexLazyRoute
}

const VezhamResourcesLazyRouteChildren: VezhamResourcesLazyRouteChildren = {
  VezhamResourcesHelpCenterLazyRoute: VezhamResourcesHelpCenterLazyRoute,
  VezhamResourcesSupportLazyRoute: VezhamResourcesSupportLazyRoute,
  VezhamResourcesIndexLazyRoute: VezhamResourcesIndexLazyRoute,
}

const VezhamResourcesLazyRouteWithChildren =
  VezhamResourcesLazyRoute._addFileChildren(VezhamResourcesLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
  VezhamFeaturesLazyRoute: VezhamFeaturesLazyRouteWithChildren,
  VezhamPricingLazyRoute: VezhamPricingLazyRoute,
  VezhamResourcesLazyRoute: VezhamResourcesLazyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
